[package]
name = "codecovsample"
version = "0.1.0"
authors = ["Will Brown <will@rebeagle.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
futures-lite = "1.11"
